cam=imread('cameraman.tif');
figure,
subplot(2, 4, 1),
imshow(myDilation2(cam, B1)), impixelinfo,
title('myDilation B1'),
subplot(2, 4, 2),
imshow(myErosion2(cam,B1)), impixelinfo,
title('myErosion B1'),
subplot(2, 4, 3),
imshow(myOpening2(cam,B1)), impixelinfo,
title('myOpening B1'),
subplot(2, 4, 4),
imshow(myClosing2(cam,B1)), impixelinfo,
title('myClosing B1'),
subplot(2, 4, 5),
imshow(myDilation2(cam, B2)), impixelinfo,
title('myDilation B2'),
subplot(2, 4, 6),
imshow(myErosion2(cam,B2)), impixelinfo,
title('myErosion B2'),
subplot(2, 4, 7),
imshow(myOpening2(cam,B2)), impixelinfo,
title('myOpening B2'),
subplot(2, 4, 8),
imshow(myClosing2(cam,B2)), impixelinfo,
title('myClosing B2'),