circbw=imread('circbw.tif');
circles=imread('circles.tif');
circlesm=imread('circlesm.tif');
figure,
subplot(2, 6, 1),
imshow(myDilation(circbw,B1)),
title('myDilation B1'),
subplot(2, 6, 2),
imshow(myDilation(circles,B1)),
title('myDilation B1'),
subplot(2, 6, 3),
imshow(myDilation(circlesm,B1)),
title('myDilation B1'),
subplot(2, 6, 4),
imshow(myErosion(circbw,B1)),
title('myErosion B1'),
subplot(2, 6, 5),
imshow(myErosion(circles,B1)),
title('myErosion B1'),
subplot(2, 6, 6),
imshow(myErosion(circlesm,B1)),
title('myErosion B1'),
subplot(2, 6, 7),
imshow(myOpening(circbw,B1)),
title('myOpening B1'),
subplot(2, 6, 8),
imshow(myOpening(circles,B1)),
title('myOpening B1'),
subplot(2, 6, 9),
imshow(myOpening(circlesm,B1)),
title('myOpening B1'),
subplot(2, 6, 10),
imshow(myClosing(circbw,B1)),
title('myClosing B1'),
subplot(2, 6, 11),
imshow(myClosing(circles,B1)),
title('myClosing B1'),
subplot(2, 6, 12),
imshow(myClosing(circlesm,B1)),
title('myClosing B1');
figure,
subplot(2, 6, 1),
imshow(myDilation(circbw,B2)),
title('myDilation B2'),
subplot(2, 6, 2),
imshow(myDilation(circles,B2)),
title('myDilation B2'),
subplot(2, 6, 3),
imshow(myDilation(circlesm,B2)),
title('myDilation B2'),
subplot(2, 6, 4),
imshow(myErosion(circbw,B2)),
title('myErosion B2'),
subplot(2, 6, 5),
imshow(myErosion(circles,B2)),
title('myErosion B2'),
subplot(2, 6, 6),
imshow(myErosion(circlesm,B2)),
title('myErosion B2'),
subplot(2, 6, 7),
imshow(myOpening(circbw,B2)),
title('myOpening B2'),
subplot(2, 6, 8),
imshow(myOpening(circles,B2)),
title('myOpening B2'),
subplot(2, 6, 9),
imshow(myOpening(circlesm,B2)),
title('myOpening B2'),
subplot(2, 6, 10),
imshow(myClosing(circbw,B2)),
title('myClosing B2'),
subplot(2, 6, 11),
imshow(myClosing(circles,B2)),
title('myClosing B2'),
subplot(2, 6, 12),
imshow(myClosing(circlesm,B2)),
title('myClosing B2');
figure,
subplot(2, 6, 1),
imshow(myDilation(circbw,B3)),
title('myDilation B3'),
subplot(2, 6, 2),
imshow(myDilation(circles,B3)),
title('myDilation B3'),
subplot(2, 6, 3),
imshow(myDilation(circlesm,B3)),
title('myDilation B3'),
subplot(2, 6, 4),
imshow(myErosion(circbw,B3)),
title('myErosion B3'),
subplot(2, 6, 5),
imshow(myErosion(circles,B3)),
title('myErosion B3'),
subplot(2, 6, 6),
imshow(myErosion(circlesm,B3)),
title('myErosion B3'),
subplot(2, 6, 7),
imshow(myOpening(circbw,B3)),
title('myOpening B3'),
subplot(2, 6, 8),
imshow(myOpening(circles,B3)),
title('myOpening B3'),
subplot(2, 6, 9),
imshow(myOpening(circlesm,B3)),
title('myOpening B3'),
subplot(2, 6, 10),
imshow(myClosing(circbw,B3)),
title('myClosing B3'),
subplot(2, 6, 11),
imshow(myClosing(circles,B3)),
title('myClosing B3'),
subplot(2, 6, 12),
imshow(myClosing(circlesm,B3)),
title('myClosing B3');